# Generated by Django 5.2.8 on 2025-12-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='connection_type',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('ethernet', 'Ethernet')], default='wifi', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('adults', 'Adults'), ('guests', 'Guests')], default='guests', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(default='unknown-device', help_text='Device hostname as reported by the router', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='Device IP address', protocol='IPv4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last time the device was seen on the network'),
        ),
        migrations.AddField(
            model_name='device',
            name='lease_remaining',
            field=models.PositiveIntegerField(default=0, help_text='DHCP lease time remaining in minutes'),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(default='0.0.0.0', help_text='MAC address of the device', max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(help_text='Phone, Laptop, TV, Console, etc.', max_length=50),
        ),
    ]
