# Generated by Django 5.2.8 on 2025-12-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_name_device_connection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='unknown', help_text='Phone, Laptop, TV, Console, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(default='unknown-device', help_text='Device hostname as reported by the router', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='Device IP address', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', help_text='MAC address of the device', max_length=17),
        ),
    ]
