# Generated by Django 5.2.8 on 2025-12-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_device_type_alter_device_hostname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('adults', 'Adults'), ('guests', 'Guests')], help_text='Device group this rule applies to', max_length=10, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('block_internet', models.BooleanField(default=False, help_text='Completely block internet access')),
                ('schedule_start', models.TimeField(blank=True, help_text='Restriction start time (e.g. 21:00)', null=True)),
                ('schedule_end', models.TimeField(blank=True, help_text='Restriction end time (e.g. 06:00)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
