# Generated by Django 5.2.8 on 2025-12-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_restrictionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('block', 'Block Internet'), ('unblock', 'Unblock Internet'), ('schedule', 'Scheduled Restriction Applied'), ('refresh', 'Router Refresh'), ('override', 'Manual Override')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional description of the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
            ],
        ),
    ]
