# Generated by Django 5.2.8 on 2025-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(help_text='Phone, Laptop, TV, Console, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(help_text='Device hostname as reported by the router', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Device IP address', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(help_text='MAC address of the device', max_length=17),
        ),
        migrations.AlterField(
            model_name='restrictionrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='restrictionrule',
            name='block_internet',
            field=models.BooleanField(default=False, help_text='Block internet access for this group'),
        ),
        migrations.AlterField(
            model_name='restrictionrule',
            name='group',
            field=models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('adults', 'Adults'), ('guests', 'Guests')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='restrictionrule',
            name='schedule_end',
            field=models.TimeField(blank=True, help_text='Restriction end time', null=True),
        ),
        migrations.AlterField(
            model_name='restrictionrule',
            name='schedule_start',
            field=models.TimeField(blank=True, help_text='Restriction start time', null=True),
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
    ]
