# Generated by Django 5.2.8 on 2025-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_device_type_alter_device_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Whether internet access is currently blocked for this device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lease_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17),
        ),
    ]
